; @title   (code "liquidz.uo")
; @format  html5

(defn _header [tag [first-char & rest-chars]]
  [tag [:span first-char] rest-chars])

(def _space "&nbsp;")
(def _dq [:span {:class "double-quote"} "\""])

(defn span [klass & body] [:span {:class klass} body])
(defn _symbol  [x]   (span "symbol" x))
(defn _keyword [x]   (span "keyword" x " "))
(defn _map     [x]   (span "map" x))
(defn _string  [& x] (span "string" _dq x _dq))
(defn _comment [& x] (span "comment" x))

[:head
 [:meta {:charset "UTF-8"}]
 [:meta {:property "og:image" :content "http://liquidz.github.com/img/site_image.png"}]
 [:meta {:property "image_src" :content "http://liquidz.github.com/img/site_image.png"}]

 [:link {:href  "/atom.xml"
         :rel   "alternate"
         :title (:title site)
         :type  "application/atom-xml"}]
 [:title (:title site)]
 (css
   "http://fonts.googleapis.com/css?family=Inconsolata"
   "/css/prettify.css"
   "/css/sunburst.css"
   "/css/main.css")]

[:body {:id "top"}
 ; github ribbon {{{
 (link
   [:img {:style "position: absolute; top: 0; right: 0; border: 0;"
          :alt "Fork me on GitHub"
          :src "https://a248.e.akamai.net/assets.github.com/img/e6bef7a091f5f3138b8cd40bc3e114258dd68ddf/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67"}]
   "https://github.com/liquidz/") ; }}}

 [:div {:class "wrapper"}
  ;; header
  [:header
   [:h1
    [:a {:href "/"}
     "(" [:span "code"] " "
     (_string "liquidz.uo")
     ")"]]]

  ;; container
  [:div {:class "container"}
   contents]

  ;; footer
  [:footer
   [:p {:class "copy"}

    (interpose
      (list _space "|" _space)
      (concat
        (map #(apply link %)
             [["Top" "/"] ["Archives" "/archives.html"]])
        (list
          (list
            (link "@uochan" "http://twitter.com/uochan")
            "&nbsp;" 2012))))]

   [:span "generated by "]
   (link (img "misaki" "/img/misaki_banner.png") "https://github.com/liquidz/misaki")
   ]]

 ;; js
 (js
   "/js/prettify.js"
   "/js/lang-clj.js"
   "/js/jquery-1.7.1.min.js"
   "/js/jquery-contained-sticky-scroll-min.js"
   "/js/coderwall.js"
   "/js/main.js")]

